= Khronos Vulkan^®^ Tutorial

== Attribution

The Khronos Vulkan^®^ Tutorial is based on the "link:https://vulkan-tutorial.com/[Vulkan Tutorial]" by Alexander Overvoorde licensed under link:https://creativecommons.org/licenses/by-sa/4.0/[CC BY-SA 4.0].

== About

This repository hosts the contents of the link:https://docs.vulkan.org/tutorial/latest[Khronos Vulkan Tutorial]. The tutorial is part of the link:https://github.com/KhronosGroup/Vulkan-Site[Vulkan Documentation Project].

== License

The contents of this repository are licensed as https://creativecommons.org/licenses/by-sa/4.0/[CC BY-SA 4.0], unless stated otherwise.
By contributing to this repository, you agree to license your contributions to the public under that same license.

The code listings in the `code` directory are licensed as https://creativecommons.org/publicdomain/zero/1.0/[CC0 1.0 Universal].
By contributing to that directory, you agree to license your contributions to the public under that same public domain-like license.

== Contributing

Contributions are welcome, details on how to contribute and the technical requirements that have to be met can be found in link:CONTRIBUTING.adoc[this document].
