:pp: {plus}{plus}

= Staging buffer

== Introduction

The vertex buffer we have right now works correctly, but the memory type that allows us to access it from the CPU may not be the most optimal memory type for the graphics card itself to read from.
The most optimal memory has the `vk::MemoryPropertyFlagBits::eDeviceLocal` flag and is usually not accessible by the CPU on dedicated graphics cards.
In this chapter, we're going to create two vertex buffers.
One _staging buffer_ in CPU accessible memory to upload the data from the vertex array to, and the final vertex buffer in device local memory.
We'll then use a buffer copy command to move the data from the staging buffer to the actual vertex buffer.

== Transfer queue

The buffer copy command requires a queue family that supports transfer operations, which is indicated using `vk::QueueFlagBits::eTransfer`.
The good news is that any queue family with `vk::QueueFlagBits::eGraphics` or `vk::QueueFlagBits::eCompute` capabilities already implicitly support `vk::QueueFlagBits::eTransfer` operations.
The implementation is not required to explicitly list it in `queueFlags` in those cases.

If you like a challenge, then you can still try to use a different queue family specifically for transfer operations.
It will require you to make the following modifications to your program:

* Introduce an `uint32_t transferQueueIndex` in addition to the `uint32_t queueIndex` (which maybe should be renamed to `graphicsQueueIndex` now), and explicitly look for a queue family with the `vk::QueueFlagBits::eTransfer` bit, but not the `vk::QueueFlagBits::eGraphics`.
* Modify `createLogicalDevice` to request a handle to a `vk::raii::Queue transferQueue' (and maybe rename the `queue` to `graphicsQueue`)
* Create a second command pool for command buffers that are submitted on the transfer queue family
* Change the `sharingMode` of resources to be `vk::SharingMode::eConcurrent` and specify both the graphics and transfer queue families
* Submit any transfer commands like `vk::raii::CommandBuffer::copyBuffer` (which we'll be using in this chapter) to the transfer queue instead of the graphics queue

It's a bit of work, but it'll teach you a lot about how resources are shared between queue families.

== Abstracting buffer creation

Because we're going to create multiple buffers in this chapter, it's a good idea to move buffer creation to a helper function.
Create a new function `createBuffer` and move the code in `createVertexBuffer` (except mapping) to it.

[,c++]
----
std::pair<vk::raii::Buffer, vk::raii::DeviceMemory> createBuffer(vk::DeviceSize size, vk::BufferUsageFlags usage, vk::MemoryPropertyFlags properties)
{
  vk::BufferCreateInfo   bufferInfo{.size = size, .usage = usage, .sharingMode = vk::SharingMode::eExclusive};
  vk::raii::Buffer       buffer          = vk::raii::Buffer(device, bufferInfo);
  vk::MemoryRequirements memRequirements = buffer.getMemoryRequirements();
  vk::MemoryAllocateInfo allocInfo{.allocationSize = memRequirements.size, .memoryTypeIndex = findMemoryType(memRequirements.memoryTypeBits, properties)};
  vk::raii::DeviceMemory bufferMemory = vk::raii::DeviceMemory(device, allocInfo);
  buffer.bindMemory(*bufferMemory, 0);
  return {std::move(buffer), std::move(bufferMemory)};
}
----

Make sure to add parameters for the buffer size, memory properties and usage so that we can use this function to create many different types of buffers.
This function returns both, the generated buffer and the device memory bound to it as a `std::pair`. As `vk::raii`-handles can't be copied, you have to move them out of this function.

You can now remove the buffer creation and memory allocation code from `createVertexBuffer` and just call `createBuffer` instead:

[,c++]
----
void createVertexBuffer()
{
  vk::DeviceSize bufferSize = sizeof(vertices[0]) * vertices.size();

  auto [stagingBuffer, stagingBufferMemory] =
      createBuffer(bufferSize, vk::BufferUsageFlagBits::eTransferSrc, vk::MemoryPropertyFlagBits::eHostVisible | vk::MemoryPropertyFlagBits::eHostCoherent);

  void *dataStaging = stagingBufferMemory.mapMemory(0, bufferSize);
  memcpy(dataStaging, vertices.data(), bufferSize);
  stagingBufferMemory.unmapMemory();
}
----

Run your program to make sure that the vertex buffer still works properly.

== Using a staging buffer

We're now going to change `createVertexBuffer` to only use a host visible buffer as temporary buffer and use a device local one as actual vertex buffer.

[,c++]
----
void createVertexBuffer()
{
  vk::DeviceSize bufferSize = sizeof(vertices[0]) * vertices.size();

  auto [stagingBuffer, stagingBufferMemory] =
      createBuffer(bufferSize, vk::BufferUsageFlagBits::eTransferSrc, vk::MemoryPropertyFlagBits::eHostVisible | vk::MemoryPropertyFlagBits::eHostCoherent);

  void *dataStaging = stagingBufferMemory.mapMemory(0, bufferSize);
  memcpy(dataStaging, vertices.data(), bufferSize);
  stagingBufferMemory.unmapMemory();

  std::tie(vertexBuffer, vertexBufferMemory) =
      createBuffer(bufferSize, vk::BufferUsageFlagBits::eVertexBuffer | vk::BufferUsageFlagBits::eTransferDst, vk::MemoryPropertyFlagBits::eDeviceLocal);

  copyBuffer(stagingBuffer, vertexBuffer, bufferSize);
}
----

We're now using a new `stagingBuffer` with `stagingBufferMemory` for mapping and copying the vertex data.
In this chapter, we're going to use two new buffer usage flags:

* `vk::BufferUsageFlagBits::eTransferSrc`: Buffer can be used as source in a memory transfer operation.
* `vk::BufferUsageFlagBits::eTransferDst`: Buffer can be used as destination in a memory transfer operation.

The `vertexBuffer` is now allocated from a memory type that is device local, which generally means that we're not able to use `vk::raii::DeviceMemory::mapMemory`.
However, we can copy data from the `stagingBuffer` to the `vertexBuffer`.
We have to indicate that we intend to do that by specifying the transfer source flag for the `stagingBuffer` and the transfer destination flag for the `vertexBuffer`, along with the vertex buffer usage flag.

We're now going to write a function to copy the contents from one buffer to another, called `copyBuffer`.

[,c++]
----
void copyBuffer(vk::raii::Buffer & srcBuffer, vk::raii::Buffer & dstBuffer, vk::DeviceSize size)
{
}
----

Memory transfer operations are executed using command buffers, just like drawing commands.
Therefore we must first allocate a temporary command buffer.
You may wish to create a separate command pool for these kinds of short-lived buffers, because the implementation may be able to apply memory allocation optimizations.
You should use the `vk::CommandPoolCreateFlagBits::eTransient` flag during command pool generation in that case.

[,c++]
----
void copyBuffer(vk::raii::Buffer & srcBuffer, vk::raii::Buffer & dstBuffer, vk::DeviceSize size)
{
  vk::CommandBufferAllocateInfo allocInfo{ .commandPool = commandPool, .level = vk::CommandBufferLevel::ePrimary, .commandBufferCount = 1 };
  vk::raii::CommandBuffer commandCopyBuffer = std::move(device.allocateCommandBuffers(allocInfo).front());
}
----

And immediately start recording the command buffer:

[,c++]
----
commandCopyBuffer.begin({.flags = vk::CommandBufferUsageFlagBits::eOneTimeSubmit});
----

We're only going to use the command buffer once and wait with returning from the function until the copy operation has finished executing.
It's good practice to tell the driver about our intent using `vk::CommandBufferUsageFlagBits::eOneTimeSubmit`.

[,c++]
----
commandCopyBuffer.copyBuffer(*srcBuffer, *dstBuffer, vk::BufferCopy(0, 0, size));
----

Contents of buffers are transferred using the `vk:raii::CommandBuffer::copyBuffer` command.
It takes the source and destination buffers as arguments, and an array of regions to copy.
The regions are defined in `vk::BufferCopy` structs and consist of a source buffer offset, destination buffer offset and size.
It is not possible to specify `vk::WholeSize` here, unlike the `vk::raii::DeviceMemory::mapMemory` command.

[,c++]
----
commandCopyBuffer.end();
----

This command buffer only contains the copy command, so we can stop recording right after that.
Now execute the command buffer to complete the transfer:

[,c++]
----
queue.submit(vk::SubmitInfo{.commandBufferCount = 1, .pCommandBuffers = &*commandCopyBuffer}, nullptr);
queue.waitIdle();
----

Unlike the draw commands, there are no events we need to wait on this time.
We just want to execute the transfer on the buffers immediately.
There are again two possible ways to wait on this transfer to complete.
We could use a fence and wait with `vk::raii::Device::waitForFences`, or simply wait for the transfer queue to become idle with `vk::raii::Queue::waitIdle`.
A fence would allow you to schedule multiple transfers simultaneously and wait for all of them complete, instead of executing one at a time.
That may give the driver more opportunities to optimize.

We can now call `copyBuffer` from the `createVertexBuffer` function to move the vertex data to the device local buffer:

[,c++]
----
copyBuffer(stagingBuffer, vertexBuffer, bufferSize);
----

After copying the data from the staging buffer to the device buffer, the RAII buffer object will clean itself up and free the memory.

Run your program to verify that you're seeing the familiar triangle again.
The improvement may not be visible right now, but its vertex data is now being loaded from high performance memory.
This will matter when we're going to start rendering more complex geometry.

== Conclusion

It should be noted that in a real world application, you're not supposed to actually call `vk::raii::Device::allocateMemory` for every individual buffer.
The maximum number of simultaneous memory allocations is limited by the `maxMemoryAllocationCount` physical device limit, which may be as low as `4096` even on high end hardware like an NVIDIA GTX 1080.
The right way to allocate memory for a large number of objects at the same time is to create a custom allocator that splits up a single allocation among many different objects by using the `offset` parameters that we've seen in many functions.

You can either implement such an allocator yourself, or use the https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator[VulkanMemoryAllocator] library provided by the GPUOpen initiative.
However, for this tutorial, it's okay to use a separate allocation for every resource, because we won't come close to hitting any of these limits for now.

In the xref:./03_Index_buffer.adoc[next chapter,] we'll learn about index buffers for vertex reuse.

link:/attachments/20_staging_buffer.cpp[C{pp} code] /
link:/attachments/19_shader_vertexbuffer.slang[slang shader] /
link:/attachments/19_shader_vertexbuffer.vert[GLSL Vertex shader] /
link:/attachments/19_shader_vertexbuffer.frag[GLSL Fragment shader]
