:pp: {plus}{plus}

= Validation layers

== What are validation layers?

The Vulkan API is designed around the idea of minimal driver overhead, and one of
the manifestations of that goal is that there is very limited error checking in
the API by default. Even mistakes as simple as setting enumerations to incorrect
values or passing null pointers to required parameters are generally not
explicitly handled beyond c{pp} type checking, and will simply result in
crashes or undefined behavior.
Because Vulkan requires you to be very explicit about everything you're doing,
it's easy to make many small mistakes like using a new GPU feature and
forgetting to request it at logical device creation time.

However, that doesn't mean that these checks can't be added to the API. Vulkan
introduces an elegant system for this known as *validation layers*. Validation
layers are optional components that hook into Vulkan function calls to apply
additional operations. Common operations in validation layers are:

* Checking the values of parameters against the specification to detect misuse
* Tracking the creation and destruction of objects to find resource leaks
* Checking thread safety by tracking the threads that calls originate from
* Logging every call and its parameters to the standard output
* Tracing Vulkan calls for profiling and replaying

Here's an example of what the implementation of a function in a diagnostics
validation layer could look like:

[,c++]
----
VkResult vkCreateInstance(
    const VkInstanceCreateInfo* pCreateInfo,
    const VkAllocationCallbacks* pAllocator,
    VkInstance* instance) {

    if (pCreateInfo == nullptr || instance == nullptr) {
        log("Null pointer passed to required parameter!");
        return VK_ERROR_INITIALIZATION_FAILED;
    }

    return real_vkCreateInstance(pCreateInfo, pAllocator, instance);
}
----

These validation layers can be freely stacked to include all the debugging
functionality that you're interested in. You can enable validation layers
for debug builds and completely disable them for release builds, which gives you
the best of both worlds!

Vulkan does not come with any validation layers built-in, but the LunarG Vulkan
SDK provides a nice set of layers that check for common errors. They're also
completely https://github.com/KhronosGroup/Vulkan-ValidationLayers[open source],
so you can check which kind of mistakes they check for and contribute. Using the
validation layers is the best way to avoid your application breaking on
different drivers by accidentally relying on undefined behavior.

Validation layers can only be used if they have been installed onto the system.
For example, the LunarG validation layers are only available on PCs with the
Vulkan SDK installed.

Other layers exist, and we recommend making use of them. We'll
leave it as an exercise to the reader to discover and try out the other
layers.  However, we recommend looking at BestPractices for more help and
suggestions about how to use Vulkan in an updated way.

There were formerly two different types of validation layers in Vulkan: instance
and device specific. The idea was that instance layers would only check
calls related to global Vulkan objects like instances, and device-specific layers
would only check calls related to a specific GPU. Device-specific layers have now been
deprecated, which means that instance validation layers apply to all Vulkan
calls.

== Using validation layers

In this section, we'll see how to enable the standard diagnostics layers provided
by the Vulkan SDK. Just like extensions, validation layers need to be enabled by
specifying their name. All the useful standard validation is bundled into a
layer included in the SDK that is known as `VK_LAYER_KHRONOS_validation`.

Let's first add two configuration variables to the program to specify the layers
to enable and whether to enable them or not. We've chosen to base that value on
whether the program is being compiled in debug mode or not. The `NDEBUG` macro
is part of the c{pp} standard and means "not debug".

[,c++]
----
constexpr uint32_t WIDTH = 800;
constexpr uint32_t HEIGHT = 600;

const std::vector<char const*> validationLayers = {
    "VK_LAYER_KHRONOS_validation"
};

#ifdef NDEBUG
constexpr bool enableValidationLayers = false;
#else
constexpr bool enableValidationLayers = true;
#endif
----

We'll check if all the requested layers are available. We need to iterate
through the requested layers and validate that all the required layers are
supported by the Vulkan implementation. This check is performed directly in the
`createInstance` function:

[source,multilang,c++,c]
.Checking for validation layer support
----
// START c++
void createInstance()
{
    ...

    // Get the required layers
    std::vector<char const*> requiredLayers;
    if (enableValidationLayers)
    {
        requiredLayers.assign(validationLayers.begin(), validationLayers.end());
    }

    // Check if the required layers are supported by the Vulkan implementation.
    auto layerProperties = context.enumerateInstanceLayerProperties();
    auto unsupportedLayerIt = std::ranges::find_if(requiredLayers,
		                                               [&layerProperties](auto const &requiredLayer) {
			                                               return std::ranges::none_of(layerProperties,
                                                                [requiredLayer](auto const &layerProperty) { return strcmp(layerProperty.layerName, requiredLayer) == 0; });
		                                               });
    if (unsupportedLayerIt != requiredLayers.end())
    {
        throw std::runtime_error("Required layer not supported: " + std::string(*unsupportedLayerIt));
    }

    ...
}
// END c++

// START c
void createInstance()
{
    ...

    // Get the required layers
    std::vector<char const*> requiredLayers;
    if (enableValidationLayers)
    {
        requiredLayers.assign(validationLayers.begin(), validationLayers.end());
    }

    // Check if the required layers are supported by the Vulkan implementation.
    uint32_t layerCount = 0;
    vkEnumerateInstanceLayerProperties(&layerCount, nullptr);
    std::vector<VkLayerProperties> layerProperties(layerCount);
    vkEnumerateInstanceLayerProperties(&layerCount, layerProperties.data());

    for (const char* requiredLayer : requiredLayers)
    {
        bool layerFound = false;
        for (const auto& layerProperty : layerProperties)
        {
            if (strcmp(layerProperty.layerName, requiredLayer) == 0)
            {
                layerFound = true;
                break;
            }
        }
        if (!layerFound)
        {
            throw std::runtime_error("Required layer not supported: " + std::string(requiredLayer));
        }
    }

    ...
}
// END c
----

== Using extensions

As already mentioned above, extensions also need to be enabled by their name. But
here, you have to distinguish between instance- and device-extensions.

We'll first create a getRequiredInstanceExtensions function that will return a
list of the required instance extensions.

[,c++]
----
std::vector<const char*> getRequiredInstanceExtensions()
{
    uint32_t glfwExtensionCount = 0;
    auto glfwExtensions = glfwGetRequiredInstanceExtensions(&glfwExtensionCount);

    std::vector extensions(glfwExtensions, glfwExtensions + glfwExtensionCount);

    return extensions;
}
----

The extensions specified by GLFW are always required, as we're working with
the GLFW dependency for windowing.

We'll check if all the required extensions are available. We first get a list of all
supported instance extensions by using the
`vk::raii::Context::enumerateInstanceExtensionProperties` function and check that all
required extensions are listed in that list. This check is also performed directly in the
`createInstance` function:

[source,multilang,c++,c]
.Checking for required instance extension support
----
// START c++
void createInstance()
{
    ...

    // Get the required extensions.
    auto requiredExtensions = getRequiredInstanceExtensions();

    // Check if the required extensions are supported by the Vulkan implementation.
    auto extensionProperties = context.enumerateInstanceExtensionProperties();
    auto unsupportedPropertyIt =
        std::ranges::find_if(requiredExtensions,
                                [&extensionProperties](auto const &requiredExtension) {
                                    return std::ranges::none_of(extensionProperties,
                                                                [requiredExtension](auto const &extensionProperty) { return strcmp(extensionProperty.extensionName, requiredExtension) == 0; });
                                });
    if (unsupportedPropertyIt != requiredExtensions.end())
    {
        throw std::runtime_error("Required extension not supported: " + std::string(*unsupportedPropertyIt));
    }

    ...
}
// END c++

// START c
void createInstance()
{
    ...

    // Get the required extensions.
    auto requiredExtensions = getRequiredInstanceExtensions();

    // Check if the required extensions are supported by the Vulkan implementation.
    uint32_t extensionCount = 0;
    vkEnumerateInstanceExtensionProperties(nullptr, &extensionCount, nullptr);
    std::vector<VkExtensionProperties> extensionProperties(extensionCount);
    vkEnumerateInstanceExtensionProperties(nullptr, &extensionCount, extensionProperties.data());

    for (const char* requiredExtension : requiredExtensions)
    {
        bool extensionFound = false;
        for (const auto& extensionProperty : extensionProperties)
        {
            if (strcmp(extensionProperty.extensionName, requiredExtension) == 0)
            {
                extensionFound = true;
                break;
            }
        }
        if (!extensionFound)
        {
            throw std::runtime_error("Required extension not supported: " + std::string(requiredExtension));
        }
    }

    ...
}
// END c
----

Now run the program in debug mode and ensure that the error does not occur. If
it does, then have a look at the FAQ.

Finally, modify the `vk::InstanceCreateInfo` struct instantiation to include the
validation layer names and the extension names:

[source,multilang,c++,c]
.Enabling the layers and extensions in InstanceCreateInfo
----
// START c++
void createInstance()
{
    ...

    vk::InstanceCreateInfo createInfo{.pApplicationInfo        = &appInfo,
                                      .enabledLayerCount       = static_cast<uint32_t>(requiredLayers.size()),
                                      .ppEnabledLayerNames     = requiredLayers.data(),
                                      .enabledExtensionCount   = static_cast<uint32_t>(requiredExtensions.size()),
                                      .ppEnabledExtensionNames = requiredExtensions.data()};
    instance = vk::raii::Instance(context, createInfo);
}
// END c++

// START c
void createInstance()
{
    ...

    VkInstanceCreateInfo createInfo{};
    createInfo.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
    createInfo.pApplicationInfo = &appInfo;
    createInfo.enabledLayerCount = static_cast<uint32_t>(requiredLayers.size());
    createInfo.ppEnabledLayerNames = requiredLayers.data();
    createInfo.enabledExtensionCount = static_cast<uint32_t>(requiredExtensions.size());
    createInfo.ppEnabledExtensionNames = requiredExtensions.data();

    if (vkCreateInstance(&createInfo, nullptr, &instance) != VK_SUCCESS) {
        throw std::runtime_error("failed to create instance!");
    }
}
// END c
----

If the check was successful then the `vk::raii::Instance` constructor should not
ever throw a `vk::Result::eErrorLayerNotPresent` error, but you should run the
program to make sure.

== Message callback

The validation layers will print debug messages to the standard output by
default, but we can also handle them ourselves by providing an explicit
callback in our program. This will also allow you to decide which kind of
messages you would like to see, because not all are necessarily (fatal)
errors. If you don't want to do that right now, then you may skip to the
last section in this chapter.

To set up a callback in the program to handle messages and the associated
details, we have to set up a debug messenger with a callback using the
`VK_EXT_debug_utils` extension.

We'll first extent the `getRequiredInstanceExtensions` function based on whether
validation layers are enabled or
not:

[source,multilang,c++,c]
.Conditionally requesting the debug utils extension
----
// START c++
std::vector<const char*> getRequiredInstanceExtensions()
{
    uint32_t glfwExtensionCount = 0;
    auto glfwExtensions = glfwGetRequiredInstanceExtensions(&glfwExtensionCount);

    std::vector extensions(glfwExtensions, glfwExtensions + glfwExtensionCount);
    if (enableValidationLayers)
    {
        extensions.push_back(vk::EXTDebugUtilsExtensionName);
    }

    return extensions;
}
// END c++

// START c
std::vector<const char*> getRequiredInstanceExtensions()
{
    uint32_t glfwExtensionCount = 0;
    const char** glfwExtensions = glfwGetRequiredInstanceExtensions(&glfwExtensionCount);

    std::vector<const char*> extensions(glfwExtensions, glfwExtensions + glfwExtensionCount);
    if (enableValidationLayers)
    {
        extensions.push_back(VK_EXT_DEBUG_UTILS_EXTENSION_NAME);
    }

    return extensions;
}
// END c
----

The debug messenger extension is conditionally added. Note that we've used the
`vk::EXTDebugUtilsExtensionName` macro here which is equal to the literal
string "VK_EXT_debug_utils". Using this macro lets you avoid typos.

Now let's see what a debug callback function looks like. Add a new static member
function called `debugCallback` with the `PFN_vkDebugUtilsMessengerCallbackEXT`
prototype. The `VKAPI_ATTR` and `VKAPI_CALL` ensure that the function has the
right signature for Vulkan to call it.

[source,multilang,c++,c]
.The debug callback function
----
// START c++
static VKAPI_ATTR vk::Bool32 VKAPI_CALL debugCallback(vk::DebugUtilsMessageSeverityFlagBitsEXT       severity,
                                                      vk::DebugUtilsMessageTypeFlagsEXT              type,
                                                      const vk::DebugUtilsMessengerCallbackDataEXT * pCallbackData,
                                                      void *                                         pUserData)
{
  std::cerr << "validation layer: type " << to_string(type) << " msg: " << pCallbackData->pMessage << std::endl;

  return vk::False;
}
// END c++

// START c
static VKAPI_ATTR VkBool32 VKAPI_CALL debugCallback(VkDebugUtilsMessageSeverityFlagBitsEXT       severity,
                                                     VkDebugUtilsMessageTypeFlagsEXT              type,
                                                     const VkDebugUtilsMessengerCallbackDataEXT * pCallbackData,
                                                     void *                                       pUserData)
{
  std::cerr << "validation layer: type " << type << " msg: " << pCallbackData->pMessage << std::endl;

  return VK_FALSE;
}
// END c
----

The first parameter specifies the severity of the message, which is one of
the following flags:

* `vk::DebugUtilsMessageSeverityFlagBitsEXT::eVerbose`: Diagnostic message from Vulkan components like the loader, layers and drivers
* `vk::DebugUtilsMessageSeverityFlagBitsEXT::eInfo`   : Informational message like the creation of a resource
* `vk::DebugUtilsMessageSeverityFlagBitsEXT::eWarning`: Message about behavior that is not necessarily an error, but very likely a bug in your application
* `vk::DebugUtilsMessageSeverityFlagBitsEXT::eError`  : Message about behavior that is invalid and may cause crashes

The values of this enumeration are set up in such a way that you can use a
comparison operation to check if a message is equal or worse compared to
some level of severity, for example:

[source,multilang,c++,c]
.Comparing severity levels
----
// START c++
if (messageSeverity >= vk::DebugUtilsMessageSeverityFlagBitsEXT::eWarning) {
    // Message is important enough to show
}
// END c++

// START c
if (messageSeverity >= VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT) {
    // Message is important enough to show
}
// END c
----

The `messageType` parameter can have the following values:

* `vk::DebugUtilsMessageTypeFlagBitsEXT::eGeneral`    : Some event has happened that is unrelated to the specification or performance
* `vk::DebugUtilsMessageTypeFlagBitsEXT::eValidation` : Something has happened that violates the specification or indicates a possible mistake
* `vk::DebugUtilsMessageTypeFlagBitsEXT::ePerformance`: Potential non-optimal use of Vulkan

The `pCallbackData` parameter refers to a `vk::DebugUtilsMessengerCallbackDataEXT` struct containing the details of the message itself, with the most important members being:

* `pMessage`   : The debug message as a null-terminated string
* `pObjects`   : Array of Vulkan object handles related to the message
* `objectCount`: Number of objects in the array

Finally, the `pUserData` parameter contains a pointer specified during the
setup of the callback and allows you to pass your own data to it.

The callback returns a boolean that indicates if the Vulkan call that triggered
the validation layer message should be aborted. If the callback returns true,
then the call is aborted with the `vk::Result::eErrorValidationFailedEXT` error. This
is normally only used to test the validation layers themselves, so you should
always return `vk::False`.

All that remains now is telling Vulkan about the callback function. Such a
callback is part of a *debug messenger*, and you can have as many of them as
you want. Add a class member for this handle right under `instance`:

[source,multilang,c++,c]
.Debug messenger class member
----
// START c++
vk::raii::DebugUtilsMessengerEXT debugMessenger = nullptr;
// END c++

// START c
VkDebugUtilsMessengerEXT debugMessenger = VK_NULL_HANDLE;
// END c
----

Now add a function `setupDebugMessenger` to be called from `initVulkan` right
after `createInstance`:

[,c++]
----
void initVulkan()
{
    createInstance();
    setupDebugMessenger();
}

void setupDebugMessenger()
{
    if (!enableValidationLayers) return;

}
----

We'll need to fill in a structure with details about the messenger and its callback:

[source,multilang,c++,c]
.Filling in the debug messenger creation info
----
// START c++
void setupDebugMessenger()
{
    ...
    vk::DebugUtilsMessageSeverityFlagsEXT severityFlags(vk::DebugUtilsMessageSeverityFlagBitsEXT::eWarning |
                                                        vk::DebugUtilsMessageSeverityFlagBitsEXT::eError);
    vk::DebugUtilsMessageTypeFlagsEXT     messageTypeFlags(
            vk::DebugUtilsMessageTypeFlagBitsEXT::eGeneral | vk::DebugUtilsMessageTypeFlagBitsEXT::ePerformance | vk::DebugUtilsMessageTypeFlagBitsEXT::eValidation);
    vk::DebugUtilsMessengerCreateInfoEXT debugUtilsMessengerCreateInfoEXT{.messageSeverity = severityFlags,
                                                                          .messageType     = messageTypeFlags,
                                                                          .pfnUserCallback = &debugCallback};
    debugMessenger = instance.createDebugUtilsMessengerEXT( debugUtilsMessengerCreateInfoEXT );
}
// END c++

// START c
void setupDebugMessenger()
{
    ...
    VkDebugUtilsMessageSeverityFlagsEXT severityFlags = VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT |
                                                         VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT;
    VkDebugUtilsMessageTypeFlagsEXT messageTypeFlags = VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT |
                                                        VK_DEBUG_UTILS_MESSAGE_TYPE_PERFORMANCE_BIT_EXT |
                                                        VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT;

    VkDebugUtilsMessengerCreateInfoEXT createInfo{};
    createInfo.sType = VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT;
    createInfo.messageSeverity = severityFlags;
    createInfo.messageType = messageTypeFlags;
    createInfo.pfnUserCallback = &debugCallback;

    // vkCreateDebugUtilsMessengerEXT is an extension function, so it isn't
    // part of the core loader and has to be looked up manually.
    auto func = reinterpret_cast<PFN_vkCreateDebugUtilsMessengerEXT>(
        vkGetInstanceProcAddr(instance, "vkCreateDebugUtilsMessengerEXT"));
    if (func == nullptr || func(instance, &createInfo, nullptr, &debugMessenger) != VK_SUCCESS)
    {
        throw std::runtime_error("failed to set up debug messenger!");
    }
}
// END c
----

The `messageSeverity` field allows you to specify all the types of
severities you would like your callback to be called for. We're only interested in messages that hint at application issues and might need fixing. So we request the `eWarning` and `eError` flags.

Similarly, the `messageType` field lets you filter which types of messages
your callback is notified about. We've simply enabled all types here. You
can always disable some if they're not useful to you.

Finally, the `pfnUserCallback` field specifies the pointer to the callback
function. You can optionally pass a pointer to the `pUserData` field which
will be passed along to the callback function via the `pUserData` parameter.
You could use this to pass a pointer to the `HelloTriangleApplication`
class, for example.

Note that there are many more ways to configure validation layer messages
and debug callbacks, but this is a good setup to get started with for this
tutorial. See the https://docs.vulkan.org/spec/latest/chapters/debugging.html#VK_EXT_debug_utils[extension specification]
for more info about the possibilities.

The complete `createInstance` function now looks like:

[source,multilang,c++,c]
.The complete createInstance function
----
// START c++
void createInstance()
{
    constexpr vk::ApplicationInfo appInfo{ .pApplicationName   = "Hello Triangle",
                .applicationVersion = VK_MAKE_VERSION( 1, 0, 0 ),
                .pEngineName        = "No Engine",
                .engineVersion      = VK_MAKE_VERSION( 1, 0, 0 ),
                .apiVersion         = vk::ApiVersion14 };

    // Get the required layers
    std::vector<char const*> requiredLayers;
    if (enableValidationLayers)
        {
            requiredLayers.assign(validationLayers.begin(), validationLayers.end());
        }

    // Check if the required layers are supported by the Vulkan implementation.
    auto layerProperties = context.enumerateInstanceLayerProperties();
    auto unsupportedLayerIt = std::ranges::find_if(requiredLayers,
                                                   [&layerProperties](auto const &requiredLayer) {
                                                       return std::ranges::none_of(layerProperties,
                                                                                   [requiredLayer](auto const &layerProperty) { return strcmp(layerProperty.layerName, requiredLayer) == 0; });
                                                   });
    if (unsupportedLayerIt != requiredLayers.end())
    {
        throw std::runtime_error("Required layer not supported: " + std::string(*unsupportedLayerIt));
    }

    // Get the required extensions.
    auto requiredExtensions = getRequiredInstanceExtensions();

    // Check if the required extensions are supported by the Vulkan implementation.
    auto extensionProperties = context.enumerateInstanceExtensionProperties();
		auto unsupportedPropertyIt =
		    std::ranges::find_if(requiredExtensions,
		                         [&extensionProperties](auto const &requiredExtension) {
			                         return std::ranges::none_of(extensionProperties,
			                                                     [requiredExtension](auto const &extensionProperty) { return strcmp(extensionProperty.extensionName, requiredExtension) == 0; });
		                         });
		if (unsupportedPropertyIt != requiredExtensions.end())
		{
			throw std::runtime_error("Required extension not supported: " + std::string(*unsupportedPropertyIt));
		}

    vk::InstanceCreateInfo createInfo{
        .pApplicationInfo        = &appInfo,
        .enabledLayerCount       = static_cast<uint32_t>(requiredLayers.size()),
        .ppEnabledLayerNames     = requiredLayers.data(),
        .enabledExtensionCount   = static_cast<uint32_t>(requiredExtensions.size()),
        .ppEnabledExtensionNames = requiredExtensions.data() };
    instance = vk::raii::Instance(context, createInfo);
}
// END c++

// START c
void createInstance()
{
    VkApplicationInfo appInfo{};
    appInfo.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO;
    appInfo.pApplicationName = "Hello Triangle";
    appInfo.applicationVersion = VK_MAKE_VERSION(1, 0, 0);
    appInfo.pEngineName = "No Engine";
    appInfo.engineVersion = VK_MAKE_VERSION(1, 0, 0);
    appInfo.apiVersion = VK_API_VERSION_1_4;

    // Get the required layers
    std::vector<char const*> requiredLayers;
    if (enableValidationLayers)
    {
        requiredLayers.assign(validationLayers.begin(), validationLayers.end());
    }

    // Check if the required layers are supported by the Vulkan implementation.
    uint32_t layerCount = 0;
    vkEnumerateInstanceLayerProperties(&layerCount, nullptr);
    std::vector<VkLayerProperties> layerProperties(layerCount);
    vkEnumerateInstanceLayerProperties(&layerCount, layerProperties.data());

    for (const char* requiredLayer : requiredLayers)
    {
        bool layerFound = false;
        for (const auto& layerProperty : layerProperties)
        {
            if (strcmp(layerProperty.layerName, requiredLayer) == 0)
            {
                layerFound = true;
                break;
            }
        }
        if (!layerFound)
        {
            throw std::runtime_error("Required layer not supported: " + std::string(requiredLayer));
        }
    }

    // Get the required extensions.
    auto requiredExtensions = getRequiredInstanceExtensions();

    // Check if the required extensions are supported by the Vulkan implementation.
    uint32_t extensionCount = 0;
    vkEnumerateInstanceExtensionProperties(nullptr, &extensionCount, nullptr);
    std::vector<VkExtensionProperties> extensionProperties(extensionCount);
    vkEnumerateInstanceExtensionProperties(nullptr, &extensionCount, extensionProperties.data());

    for (const char* requiredExtension : requiredExtensions)
    {
        bool extensionFound = false;
        for (const auto& extensionProperty : extensionProperties)
        {
            if (strcmp(extensionProperty.extensionName, requiredExtension) == 0)
            {
                extensionFound = true;
                break;
            }
        }
        if (!extensionFound)
        {
            throw std::runtime_error("Required extension not supported: " + std::string(requiredExtension));
        }
    }

    VkInstanceCreateInfo createInfo{};
    createInfo.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
    createInfo.pApplicationInfo = &appInfo;
    createInfo.enabledLayerCount = static_cast<uint32_t>(requiredLayers.size());
    createInfo.ppEnabledLayerNames = requiredLayers.data();
    createInfo.enabledExtensionCount = static_cast<uint32_t>(requiredExtensions.size());
    createInfo.ppEnabledExtensionNames = requiredExtensions.data();

    if (vkCreateInstance(&createInfo, nullptr, &instance) != VK_SUCCESS) {
        throw std::runtime_error("failed to create instance!");
    }
}
// END c
----

== Configuration

There are a lot more settings for the behavior of validation layers than just
the flags specified in the `vk::DebugUtilsMessengerCreateInfoEXT` struct. Browse
to the Vulkan SDK and go to the `Config` directory. There you will find a
`vk_layer_settings.txt` file that explains how to configure the layers.

To configure the layer settings for your own application, copy the file to the
`Debug` and `Release` directories of your project and follow the instructions to
set the desired behavior. However, for the remainder of this tutorial, We will
assume that you're using the default settings.

Throughout this tutorial, we will be making a couple of intentional mistakes
to show you how helpful the validation layers are with catching them and to teach you
how important it is to know exactly what you're doing with Vulkan. Now it's time
to look at xref:./03_Physical_devices_and_queue_families.adoc[Vulkan devices in the system].

link:/attachments/02_validation_layers.cpp[C{pp} code]
