:pp: {plus}{plus}

= Window surface

Since Vulkan is a platform-agnostic API, it is not designed to interface
directly with the window system on its own. To establish the connection
between Vulkan and the window system to present results to the screen, we
need to use the WSI (Window System Integration) extensions. In this chapter
we'll discuss the first one, which is `VK_KHR_surface`. It exposes a
`VkSurfaceKHR` object that represents an abstract type of surface to
present rendered images to. The surface in our program will be backed by
the window that we've already opened with GLFW.

The `VK_KHR_surface` extension is an instance level extension, and we've actually
already enabled it, because it's included in the list returned by
`glfwGetRequiredInstanceExtensions`. The list also includes some other WSI
extensions that we'll use in the next couple of chapters.

The window surface needs to be created right after the instance creation,
because it can actually influence the physical device selection. The reason we
postponed this is that window surfaces are part of the larger topic of
render targets and presentation for which the explanation would have cluttered
the basic setup. It should also be noted that window surfaces are an entirely
optional component in Vulkan if you just need off-screen rendering. Vulkan
allows you to do that without hacks like creating an invisible window
(necessary for OpenGL).  Vulkan also allows you to remotely render from a
non-presenting GPU or remotely over the internet, or run compute
acceleration for AI without a render or presentation target.

While GLFW will be demonstrated here, the concept of Vulkan rendering to a
surface is repeated as a target for any other Windowing API. This concept
applies to mobile and to work with direct access to the windowing manager.
That said, let's for now, concentrate on GLFW and see how it concretely
works in this tutorial.

== Window surface creation

Start by adding a `surface` class member right below the debug callback.

[,c++]
----
vk::raii::SurfaceKHR surface = nullptr;
----

Although the `VkSurfaceKHR` object and its usage is platform-agnostic, its
creation isn't because it depends on window system details. For example, it
needs the `HWND` and `HMODULE` handles on Windows. Therefore, there is a
platform-specific addition to the extension, which on Windows is called
`VK_KHR_win32_surface` and is also automatically included in the list from
`glfwGetRequiredInstanceExtensions`.

I will demonstrate how this platform-specific extension can be used to create a
surface on Windows, but we won't use it in this tutorial. It doesn't
make any sense to use a library like GLFW and then proceed to use
platform-specific code anyway. GLFW actually has `glfwCreateWindowSurface` that
handles the platform differences for us. Still, it's good to see what it does
behind the scenes before we start relying on it.

To access native platform functions, you need to update the includes at the top:

[,c++]
----
#define VK_USE_PLATFORM_WIN32_KHR
#define GLFW_INCLUDE_VULKAN
#include <GLFW/glfw3.h>
#define GLFW_EXPOSE_NATIVE_WIN32
#include <GLFW/glfw3native.h>
----

Because a window surface is a Vulkan object, it comes with a
`vk::Win32SurfaceCreateInfoKHR` struct that needs to be filled in. It has two
important parameters: `hwnd` and `hinstance`. These are the handles to the
window and the process.

[,c++]
----
vk::Win32SurfaceCreateInfoKHR createInfo{.hinstance = GetModuleHandle(nullptr),
                                         .hwnd      = glfwGetWin32Window(window)};
----

The `glfwGetWin32Window` function is used to get the raw `HWND` from the GLFW
window object. The `GetModuleHandle` call returns the `HINSTANCE` handle of the
current process.

After that the surface can be created with `vk::raii::Instance::createWin32SurfaceKHR`,
which includes a parameter for surface creation details and custom allocators.
Technically, this is a WSI extension function, but it is so commonly used
that the standard Vulkan loader includes it, so unlike other extensions, you
don't need to explicitly load it.

[,c++]
----
surface = instance.createWin32SurfaceKHR(createInfo);
----

The process is similar for other platforms like Linux, where
`vk::raii::Instance::createXcbSurfaceKHR` takes an XCB connection and window as creation details
with X11.

The `glfwCreateWindowSurface` function performs exactly this operation with a
different implementation for each platform. We'll now integrate it into our
program. Add a function `createSurface` to be called from `initVulkan` right
after instance creation and `setupDebugMessenger`.

[,c++]
----
void initVulkan() {
    createInstance();
    setupDebugMessenger();
    createSurface();
    pickPhysicalDevice();
    createLogicalDevice();
}

void createSurface() {

}
----

The GLFW call takes simple parameters instead of a struct which makes the
implementation of the function very straightforward:

[,c++]
----
void createSurface() {
    VkSurfaceKHR       _surface;
    if (glfwCreateWindowSurface(*instance, window, nullptr, &_surface) != 0) {
        throw std::runtime_error("failed to create window surface!");
    }
    surface = vk::raii::SurfaceKHR(instance, _surface);
}
----

However, as you see in the above, GLFW only deals with the Vulkan C API.
The VkSurfaceKHR object is a C API object.  Thankfully, it can natively be
promoted to the C++ wrapper, and that's what we do here.

The parameters are the `VkInstance`, GLFW window pointer, custom allocators and
pointer to a `VkSurfaceKHR` variable. It simply passes through the `VkResult` from
the relevant platform call. GLFW doesn't offer a special function for destroying
a surface, but wrapping it in our raii SurfaceKHR object will let Vulkan
RAII take care of that for us.

== Querying for presentation support

Although the Vulkan implementation may support window system integration, that
does not mean that every device in the system supports it. Therefore, we need to
extend `createLogicalDevice` to ensure that a device can present images to the
surface we created. Since the presentation is a queue-specific feature, the
problem is actually about finding a queue family that supports presenting to the
surface we created.

It's actually possible but very unlikely that the queue families supporting graphics
commands and the queue families supporting presentation do not overlap. But for simplicity
we assume, there is such a queue family, and bail out in case there isn't.

That is, next, we'll look for a queue family that has the capability of both, supporting
graphics operations, and presenting to our window surface. The function to check for present
support is `vk::raii::PhysicalDevice::getSurfaceSupportKHR`, which takes the queue family
index and the surface as parameters:

[,c++]
----
uint32_t queueIndex = ~0;
for (uint32_t qfpIndex = 0; qfpIndex < queueFamilyProperties.size(); qfpIndex++)
{
  if ((queueFamilyProperties[qfpIndex].queueFlags & vk::QueueFlagBits::eGraphics) &&
      physicalDevice.getSurfaceSupportKHR(qfpIndex, *surface))
  {
    // found a queue family that supports both graphics and present
    queueIndex = qfpIndex;
    break;
  }
}
if (queueIndex == ~0)
{
  throw std::runtime_error("Could not find a queue for graphics and present -> terminating");
}
----

== Creating the presentation queue

The one thing that remains is modifying the logical device creation procedure to
create the queue and retrieve the `vk::raii::Queue` handle. We need to modify the
filtering logic to find the best queue families to use as we detect them.  Here's
how we do it in one function at the device creation functions:

[,c++]
----
void createLogicalDevice() {
    // find the index of the first queue family that supports graphics
    std::vector<vk::QueueFamilyProperties> queueFamilyProperties = physicalDevice.getQueueFamilyProperties();

    // get the first index into queueFamilyProperties which supports both graphics and present
    uint32_t queueIndex = ~0;
    for (uint32_t qfpIndex = 0; qfpIndex < queueFamilyProperties.size(); qfpIndex++)
    {
      if ((queueFamilyProperties[qfpIndex].queueFlags & vk::QueueFlagBits::eGraphics) &&
          physicalDevice.getSurfaceSupportKHR(qfpIndex, *surface))
      {
        // found a queue family that supports both graphics and present
        queueIndex = qfpIndex;
        break;
      }
    }
    if (queueIndex == ~0)
    {
      throw std::runtime_error("Could not find a queue for graphics and present -> terminating");
    }

    // query for Vulkan 1.3 features
		vk::StructureChain<vk::PhysicalDeviceFeatures2,
		                   vk::PhysicalDeviceVulkan11Features,
		                   vk::PhysicalDeviceVulkan13Features,
		                   vk::PhysicalDeviceExtendedDynamicStateFeaturesEXT>
		    featureChain = {
		        {},                                    // vk::PhysicalDeviceFeatures2
		        {.shaderDrawParameters = true},        // vk::PhysicalDeviceVulkan11Features
		        {.dynamicRendering = true},            // vk::PhysicalDeviceVulkan13Features
		        {.extendedDynamicState = true}         // vk::PhysicalDeviceExtendedDynamicStateFeaturesEXT
		    };

    // create a Device
    float                     queuePriority = 0.5f;
    vk::DeviceQueueCreateInfo deviceQueueCreateInfo{.queueFamilyIndex = queueIndex, .queueCount = 1, .pQueuePriorities = &queuePriority};
    vk::DeviceCreateInfo      deviceCreateInfo{.pNext                   = &featureChain.get<vk::PhysicalDeviceFeatures2>(),
                                               .queueCreateInfoCount    = 1,
                                               .pQueueCreateInfos       = &deviceQueueCreateInfo,
                                               .enabledExtensionCount   = static_cast<uint32_t>(requiredDeviceExtension.size()),
                                               .ppEnabledExtensionNames = requiredDeviceExtension.data()};

    device = vk::raii::Device( physicalDevice, deviceCreateInfo );
    queue  = vk::raii::Queue(device, queueIndex, 0);
}
----

In the xref:./01_Swap_chain.adoc[next chapter], we're going to look at swap chains and
how they allow us to present images to the surface.

link:/attachments/05_window_surface.cpp[C{pp} code]
