:pp: {plus}{plus}

= Frames in flight

Right now our render loop has one glaring flaw.
We are required to wait on the previous frame to finish before we can start rendering the next which results in unnecessary idling of the host.

// insert diagram showing our current render loop and the 'multi frame in flight' render loop

The way to fix this is to allow multiple frames to be _in-flight_ at once, that  is to say, allow the rendering of one frame to not interfere with the recording of the next.
How do we do this?
Any resource that is accessed and modified during rendering must be duplicated.
Thus, we need multiple command buffers, semaphores, and fences.
In later chapters, we will also add multiple instances of other resources, so we will see this concept reappear.

Start by adding a constant at the top of the program that defines how many frames should be processed concurrently:

[,c++]
----
constexpr int MAX_FRAMES_IN_FLIGHT = 2;
----

We choose the number 2 because we don't want the CPU to get _too_ far ahead of the GPU.
With two frames in flight, the CPU and the GPU can be working on their own tasks at the same time.
If the CPU finishes early, it will wait till the GPU finishes rendering before submitting more work.
With three or more frames in flight, the CPU could get ahead of the GPU, adding frames of latency.
Generally, extra latency isn't desired.
But giving the application control over the number of frames in flight is another example of Vulkan being explicit.

Each frame should have its own command buffer, set of semaphores, and fence.
Rename and then change them to be ``std::vector``s of the objects:

[source,multilang,c++,c]
.Per-frame synchronization object vectors
----
// START c++
std::vector<vk::raii::CommandBuffer> commandBuffers;

...

std::vector<vk::raii::Semaphore> presentCompleteSemaphores;
std::vector<vk::raii::Semaphore> renderFinishedSemaphores;
std::vector<vk::raii::Fence> inFlightFences;
// END c++

// START c
std::vector<VkCommandBuffer> commandBuffers;

...

std::vector<VkSemaphore> presentCompleteSemaphores;
std::vector<VkSemaphore> renderFinishedSemaphores;
std::vector<VkFence> inFlightFences;
// END c
----

Then we need to create multiple command buffers.
Rename `createCommandBuffer` to `createCommandBuffers`.
Next we need to resize the command buffers vector to the size of `MAX_FRAMES_IN_FLIGHT`, alter the `vk::CommandBufferAllocateInfo` to contain that many command buffers, and then change the destination to our vector of command buffers:

[source,multilang,c++,c]
.createCommandBuffers
----
// START c++
void createCommandBuffers()
{
		vk::CommandBufferAllocateInfo allocInfo{.commandPool = commandPool, .level = vk::CommandBufferLevel::ePrimary, .commandBufferCount = MAX_FRAMES_IN_FLIGHT};
    commandBuffers = vk::raii::CommandBuffers( device, allocInfo );
}
// END c++

// START c
void createCommandBuffers()
{
    VkCommandBufferAllocateInfo allocInfo{};
    allocInfo.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
    allocInfo.commandPool = commandPool;
    allocInfo.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
    allocInfo.commandBufferCount = MAX_FRAMES_IN_FLIGHT;

    commandBuffers.resize(MAX_FRAMES_IN_FLIGHT);
    if (vkAllocateCommandBuffers(device, &allocInfo, commandBuffers.data()) != VK_SUCCESS) {
        throw std::runtime_error("failed to allocate command buffers!");
    }
}
// END c
----

The `createSyncObjects` function should be changed to create all the objects:

[source,multilang,c++,c]
.createSyncObjects (per frame)
----
// START c++
void createSyncObjects()
{
		assert(presentCompleteSemaphores.empty() && renderFinishedSemaphores.empty() && inFlightFences.empty());

		for (size_t i = 0; i < swapChainImages.size(); i++)
		{
			renderFinishedSemaphores.emplace_back(device, vk::SemaphoreCreateInfo());
		}

		for (size_t i = 0; i < MAX_FRAMES_IN_FLIGHT; i++)
		{
			presentCompleteSemaphores.emplace_back(device, vk::SemaphoreCreateInfo());
			inFlightFences.emplace_back(device, vk::FenceCreateInfo{.flags = vk::FenceCreateFlagBits::eSignaled});
		}
}
// END c++

// START c
void createSyncObjects()
{
    assert(presentCompleteSemaphores.empty() && renderFinishedSemaphores.empty() && inFlightFences.empty());

    VkSemaphoreCreateInfo semaphoreInfo{};
    semaphoreInfo.sType = VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO;

    VkFenceCreateInfo fenceInfo{};
    fenceInfo.sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO;
    fenceInfo.flags = VK_FENCE_CREATE_SIGNALED_BIT;

    renderFinishedSemaphores.resize(swapChainImages.size());
    for (size_t i = 0; i < swapChainImages.size(); i++)
    {
        if (vkCreateSemaphore(device, &semaphoreInfo, nullptr, &renderFinishedSemaphores[i]) != VK_SUCCESS) {
            throw std::runtime_error("failed to create synchronization objects for a frame!");
        }
    }

    presentCompleteSemaphores.resize(MAX_FRAMES_IN_FLIGHT);
    inFlightFences.resize(MAX_FRAMES_IN_FLIGHT);
    for (size_t i = 0; i < MAX_FRAMES_IN_FLIGHT; i++)
    {
        if (vkCreateSemaphore(device, &semaphoreInfo, nullptr, &presentCompleteSemaphores[i]) != VK_SUCCESS ||
            vkCreateFence(device, &fenceInfo, nullptr, &inFlightFences[i]) != VK_SUCCESS) {
            throw std::runtime_error("failed to create synchronization objects for a frame!");
        }
    }
}
// END c
----

To use the right objects every frame, we need to keep track of the current frame.
We will use a frame index for that purpose:

[,c++]
----
uint32_t frameIndex = 0;
----

The `drawFrame` function can now be modified to use the right objects:

[source,multilang,c++,c]
.drawFrame using per-frame indices
----
// START c++
void drawFrame() {
		auto fenceResult = device.waitForFences(*inFlightFences[frameIndex], vk::True, UINT64_MAX);
		if (fenceResult != vk::Result::eSuccess)
		{
			throw std::runtime_error("failed to wait for fence!");
		}
		device.resetFences(*inFlightFences[frameIndex]);

		auto [result, imageIndex] = swapChain.acquireNextImage(UINT64_MAX, *presentCompleteSemaphores[frameIndex], nullptr);

		commandBuffers[frameIndex].reset();
		recordCommandBuffer(imageIndex);

		vk::PipelineStageFlags waitDestinationStageMask(vk::PipelineStageFlagBits::eColorAttachmentOutput);
		const vk::SubmitInfo   submitInfo{.waitSemaphoreCount   = 1,
		                                  .pWaitSemaphores      = &*presentCompleteSemaphores[frameIndex],
		                                  .pWaitDstStageMask    = &waitDestinationStageMask,
		                                  .commandBufferCount   = 1,
		                                  .pCommandBuffers      = &*commandBuffers[frameIndex],
		                                  .signalSemaphoreCount = 1,
		                                  .pSignalSemaphores    = &*renderFinishedSemaphores[imageIndex]};
		queue.submit(submitInfo, *inFlightFences[frameIndex]);
}
// END c++

// START c
void drawFrame() {
    if (vkWaitForFences(device, 1, &inFlightFences[frameIndex], VK_TRUE, UINT64_MAX) != VK_SUCCESS)
    {
        throw std::runtime_error("failed to wait for fence!");
    }
    vkResetFences(device, 1, &inFlightFences[frameIndex]);

    uint32_t imageIndex;
    VkResult result = vkAcquireNextImageKHR(device, swapChain, UINT64_MAX, presentCompleteSemaphores[frameIndex], VK_NULL_HANDLE, &imageIndex);

    vkResetCommandBuffer(commandBuffers[frameIndex], 0);
    recordCommandBuffer(imageIndex);

    VkPipelineStageFlags waitDestinationStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
    VkSubmitInfo submitInfo{};
    submitInfo.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
    submitInfo.waitSemaphoreCount = 1;
    submitInfo.pWaitSemaphores = &presentCompleteSemaphores[frameIndex];
    submitInfo.pWaitDstStageMask = &waitDestinationStageMask;
    submitInfo.commandBufferCount = 1;
    submitInfo.pCommandBuffers = &commandBuffers[frameIndex];
    submitInfo.signalSemaphoreCount = 1;
    submitInfo.pSignalSemaphores = &renderFinishedSemaphores[imageIndex];

    if (vkQueueSubmit(queue, 1, &submitInfo, inFlightFences[frameIndex]) != VK_SUCCESS) {
        throw std::runtime_error("failed to submit draw command buffer!");
    }
}
// END c
----

Of course, we shouldn't forget to advance to the next frame every time:

[,c++]
----
void drawFrame() {
    ...

    frameIndex = (frameIndex + 1) % MAX_FRAMES_IN_FLIGHT;
}
----

By using the modulo (%) operator, we ensure that the frame index loops around after every `MAX_FRAMES_IN_FLIGHT` enqueued frames.

////
Possibly use swapchain-image-count for renderFinished semaphores, as it can't
be known with a fence whether the semaphore is ready for re-use.
////

We've now implemented all the necessary synchronization to ensure that there
are no more than `MAX_FRAMES_IN_FLIGHT` frames of work enqueued and that
these frames are not stepping over each other.
Note that it is fine for other parts of the code, like the final cleanup, to rely on more rough synchronization like `vk::raii::Device::waitIdle`.
You should decide on which approach to use based on performance requirements.

Additionally, we could use timeline semaphores instead of the binary
semaphores presented here.  To see an example of how to use timeline
semaphores, look at xref:../../11_Compute_Shader.adoc[compute shader chapter]
.  Note that timeline semaphores are especially useful for dealing with a
compute and a graphics queue as in that example.  This method of simple
binary semaphores could be thought of as the more traditional approach to
synchronization.

To learn more about synchronization through examples, have a look at https://github.com/KhronosGroup/Vulkan-Docs/wiki/Synchronization-Examples#swapchain-image-acquire-and-present[this extensive overview] by Khronos.

In the xref:../03_Drawing_a_triangle/04_Swap_chain_recreation.adoc[next
chapter] we'll deal with one more small thing required for a well-behaved Vulkan program.

link:/attachments/16_frames_in_flight.cpp[C{pp} code] /
link:/attachments/09_shader_base.slang[Slang shader] /
link:/attachments/09_shader_base.vert[GLSL Vertex shader] /
link:/attachments/09_shader_base.frag[GLSL Fragment shader]
